export const vocabDay24 = [
  [1, "factor", "요소, 요인"],
  [2, "facility", "시설, 설비, 편의"],
  [3, "facilitate", "가능하게 하다"],
  [4, "facilitator", "조력자, 촉진제"],
  [5, "faculty", "능력, 대학의 교수진"],
  [6, "difficulty", "어려움, 곤경"],
  [7, "difficult", "어려운"],
  [8, "have difficulty with", "~에 어려움을 겪다"],
  [9, "factual", "사실의, 사실에 근거한"],
  [10, "fact", "사실"],
  [11, "affect", "영향을 미치다"],
  [12, "affection", "영향, 작용, 애정"],
  [13, "affective", "감정의, 정서적인"],
  [14, "effect", "영향, 효과, 결과"],
  [15, "effective", "효과적인"],
  [16, "effectively", "효과적으로"],
  [17, "ineffective", "효과 없는"],
  [18, "have an effect on", "~에 영향을 미치다"],
  [19, "consequence", "결과, 영향"],
  [20, "outcome", "결과, 성과"],
  [21, "result", "결과, 성과"],
  [22, "defect", "결함, 결점, 부족"],
  [23, "defective", "결함이 있는"],
  [24, "infect", "감염시키다, 전염시키다, 오염시키다"],
  [25, "infection", "감염, 전염병"],
  [26, "infectious", "전염되는"],
  [27, "be infected with", "~에 감염되다"],
  [28, "sufficient", "충분한"],
  [29, "sufficiently", "충분히"],
  [30, "sufficiency", "충분함, 충분한 양"],
  [31, "insufficient", "불충분한"],
  [32, "efficient", "효율이 좋은, 효과 있는, 유능한"],
  [33, "efficiently", "효율적으로, 효과적으로"],
  [34, "efficiency", "효율, 능률"],
  [35, "inefficient", "비효율적인"],
  [36, "fiction", "소설, 허구"],
  [37, "fictionalize", "소설화하다"],
  [38, "deficit", "적자, 부족액, 결손"],
  [39, "deficient", "부족한, 결핍된"],
  [40, "deficiency", "결핍, 부족"],
  [41, "magnificent", "웅장한, 장엄한, 위대한"],
  [42, "magnificently", "웅장하게, 장대하게"],
  [43, "proficient", "능숙한, 숙달한; 숙련한 사람"],
  [44, "proficiency", "능숙, 숙달"],
  [45, "profit", "이익, 수익, 이윤; 이익을 얻다, ~의 이익이 되다"],
  [46, "profitable", "유익한"],
  [47, "non-profit organization", "비영리 기관"],
  [48, "feat", "공적, 위업, 재주"],
  [49, "feature", "특징, 기능; 특색으로 삼다"],
  [50, "defeat", "패배시키다; 패배, 실패"],
  [51, "defeated", "패배한"],
  [52, "counterfeit", "위조하다; 위조의, 가짜의; 위조품, 가짜"],
  [53, "perfect", "완벽한, 더할 나위 없는, 완전한"],
  [54, "benefit", "이익, 이득; 이익을 얻다"],
  [55, "structure", "구조물, 건축물; 구조화하다"],
  [56, "structural", "구조적인"],
  [57, "construct", "건설하다, 세우다, 구성하다"],
  [58, "constructive", "건설적인"],
  [59, "construction", "건설"],
  [60, "reconstruct", "재건하다, 복원하다"],
  [61, "reconstruction", "재건, 복원"],
  [62, "destruction", "파괴, 파멸, 말살"],
  [63, "destruct", "자폭시키다, 파괴되다"],
  [64, "destructive", "파괴적인"],
  [65, "instruct", "가르치다, 지시하다, 명령하다"],
  [66, "instructor", "강사, 교사"],
  [67, "instruction", "설명, 지시"],
  [68, "instruct A in B", "A에게 B를 가르치다"],
  [69, "instrument", "도구, 수단, 악기"],
  [70, "obstruct", "막다, 방해하다"],
  [71, "obstruction", "방해, 차단"],
  [72, "obstructive", "방해하는"],
  [73, "destroy", "파괴하다, 말살하다"],
  [74, "industry", "산업계, 제조업, 근면성"],
  [75, "industrial", "산업의"],
  [76, "industrialize", "산업화하다"],
  [77, "industrialization", "산업화"]
] as const;
