export const vocabDay20 = [
  [1, "port", "항구, 항구 도시"],
  [2, "opportunity", "좋은 기회, 호기"],
  [3, "support", "지지하다, 지원하다, 대변하다; 지지, 지원, 후원"],
  [4, "supporter", "지지자"],
  [5, "supportive", "지지하는, 도와주는"],
  [6, "export", "수출품, 수출액; 수출하다"],
  [7, "exporter", "수출업자"],
  [8, "exportable", "수출할 수 있는"],
  [9, "import", "수입품; 수입하다"],
  [10, "importation", "수입, 수입품"],
  [11, "importer", "수입업자"],
  [12, "importable", "수입할 수 있는"],
  [13, "importantly", "중요하게"],
  [14, "important", "중요한"],
  [15, "portable", "휴대용의, 휴대가 쉬운; 휴대용 제품"],
  [16, "transport", "수송하다, 운송하다; 수송, 운송"],
  [17, "navy", "해군, 짙은 남색"],
  [18, "naval", "해군의"],
  [19, "navigate", "항해하다, 길을 찾다, 운전하다"],
  [20, "navigator", "항해자, 조종사"],
  [21, "navigation", "항해술, 조종술"],
  [22, "career", "전문적 직업, 경력; 직업적인, 전문적인"],
  [23, "carpenter", "목수"],
  [24, "carrier", "운송인, 운송 회사, 매개체"],
  [25, "carriage", "마차, 운반, 수송"],
  [26, "charge", "요금, 책임; 요금을 청구하다, 일을 맡기다, 충전하다"],
  [27, "recharge", "재충전하다"],
  [28, "rechargeable", "재충전되는"],
  [29, "free of charge", "무료로"],
  [30, "in charge of", "~에 책임이 있는, ~을 담당하는"],
  [31, "discharge", "방출하다, 해고하다; 방출물, 해고, 이행"],
  [32, "fort", "요새, 성채, 군의 주둔지"],
  [33, "fortify", "요새화하다, 강화하다"],
  [34, "fortress", "요새"],
  [35, "effort", "노력의 성과, 수고"],
  [36, "effortless", "노력하지 않는, 쉬운"],
  [37, "effortlessly", "노력하지 않고, 쉽게"],
  [38, "in an effort to", "~해보려는 노력으로"],
  [39, "make an effort (to)", "~하려는 노력을 하다"],
  [40, "comfort", "편안함, 위안; 위로하다"],
  [41, "comfortable", "편안한"],
  [42, "comfortably", "편안하게"],
  [43, "uncomfortable", "불편한"],
  [44, "discomfort", "불편, 가벼운 통증"],
  [45, "force", "힘, 폭력; 강요하다, 억지로 ~시키다"],
  [46, "forceful", "강력한, 강압적인"],
  [47, "be forced to", "~하도록 강요받다"],
  [48, "force A to B", "A에게 B하도록 강요하다"],
  [49, "workforce", "노동력, 노동자"],
  [50, "enforce", "강요하다, 법 등을 집행하다, 시행하다"],
  [51, "enforcement", "강제, 집행, 시행"],
  [52, "enforceable", "집행할 수 있는"],
  [53, "reinforce", "강화하다, 보강하다"],
  [54, "reinforcement", "강화, 보강"],
  [55, "potent", "강한, 영향력/효력 있는"],
  [56, "potential", "가능성 있는, 잠재적인"],
  [57, "potentially", "가능성 있게, 잠재적으로"],
  [58, "dominant", "지배적인, 우세한"],
  [59, "influential", "영향력이 있는"],
  [60, "powerful", "강력한, 우위한"],
  [61, "possible", "가능한, 있을 수 있는"],
  [62, "possibly", "아마"],
  [63, "possibility", "가능성"],
  [64, "as soon as possible", "가능한 한 빨리"],
  [65, "impossible", "불가능한, 있을 수 없는"],
  [66, "impossibly", "불가능하게"],
  [67, "possess", "소유하다, 능력 등을 지니다"],
  [68, "possession", "소유물, 소지품"],
  [69, "empower", "권한을 주다, 권력을 위임하다"],
  [70, "overpower", "제압하다, 압도하다"],
  [71, "dynamic", "역동적인; 역학, 원동력"],
  [72, "dynamics", "역학 관계, 동역학, 원동력"],
  [73, "dynasty", "왕가, 왕조, 왕조의 통치 기간"]
] as const;
