export const vocabDay18 = [
  [1, "attract", "관심 등을 끌다, 끌어모으다"],
  [2, "attraction", "끌림, 매력"],
  [3, "attractive", "마음을 끄는, 매력적인"],
  [4, "unattractive", "매력적이지 않은"],
  [5, "contract", "계약하다, 수축하다; 계약서"],
  [6, "contraction", "수축, 축소"],
  [7, "contractor", "계약자"],
  [8, "distract", "주의를 산만하게 하다"],
  [9, "distraction", "집중을 방해하는 것, 주의 산만"],
  [10, "abstract", "추출하다, 끌어내다; 추상적인; 추상 개념"],
  [11, "abstraction", "추상적 개념"],
  [12, "abstractive", "추상적인"],
  [13, "extract", "추출하다, 발췌하다; 추출물, 발췌"],
  [14, "extraction", "뽑아냄, 추출"],
  [15, "subtract", "빼다, 덜다"],
  [16, "subtraction", "뺄셈, 감산, 공제"],
  [17, "track", "길, 선로, 경주로; 추적하다"],
  [18, "tracker", "추적자"],
  [19, "keep track of", "~을 놓치지 않도록 하다, ~을 추적하다"],
  [20, "lose track of", "~을 놓치다"],
  [21, "trace", "자취, 흔적; 추적하다, 따라가다"],
  [22, "traceable", "추적할 수 있는"],
  [23, "trade", "거래, 무역; 거래하다, 교역하다"],
  [24, "trail", "자국, 시골길, 특정한 코스; 뒤쫓다"],
  [25, "trait", "특성, 특징"],
  [26, "attribute", "특성, 속성"],
  [27, "characteristic", "특성, 특징"],
  [28, "feature", "특징, 기능"],
  [29, "portray", "묘사하다, 그리다, 보여주다"],
  [30, "portrait", "묘사, 초상화"],
  [31, "treat", "대하다, 다루다, 치료하다; 대접"],
  [32, "treatment", "대우, 치료"],
  [33, "retreat", "후퇴하다, 물러나다; 후퇴, 철수, 휴양 시설"],
  [34, "treaty", "조약, 협정"],
  [35, "produce", "생산하다, 제작하다"],
  [36, "product", "생산물, 제품"],
  [37, "production", "생산"],
  [38, "productive", "생산적인"],
  [39, "productivity", "생산성"],
  [40, "reproduce", "재생하다, 번식하다, 복사하다"],
  [41, "reproduction", "재생, 번식, 복사"],
  [42, "reduce", "줄이다, 감소하다"],
  [43, "reduction", "축소, 감소"],
  [44, "education", "교육 기관, 교육학"],
  [45, "educational", "교육적인"],
  [46, "educate", "교육하다"],
  [47, "educator", "교육자"],
  [48, "conduct", "이끌다, 지휘하다, 실시하다; 지도, 행위, 품행"],
  [49, "conductor", "지휘자"],
  [50, "induce", "유도하다, 유발하다, 설득하다"],
  [51, "inducement", "유인책"],
  [52, "induction", "유도, 유발"],
  [53, "deduce", "추론하다, 연역하다"],
  [54, "deduction", "추론, 연역, 공제액"],
  [55, "by-product", "부산물, 부작용"],
  [56, "introduction", "도입, 소개, 서론"],
  [57, "compel", "강요하다, 억지로 ~하게 하다"],
  [58, "compulsion", "강요, 충동"],
  [59, "compulsory", "강제적인, 의무적인"],
  [60, "compel A to B", "A에게 B하도록 강요하다"],
  [61, "propel", "나아가게 하다, 추진하다"],
  [62, "propeller", "추진기, 프로펠러"],
  [63, "propulsion", "추진"],
  [64, "expel", "쫓아내다, 추방하다, 배출하다"],
  [65, "expulsion", "추방, 배출"],
  [66, "expulsive", "추방하는, 배제적인"],
  [67, "repel", "쫓아버리다, 물리치다"],
  [68, "repellent", "물리치는, 혐오감을 주는; 반발력, 방충제"],
  [69, "appeal", "관심을 끌다, 호소하다; 호소, 매력"],
  [70, "appealing", "매력적인"],
  [71, "pulse", "맥박, 진동, 파동; 맥박치다"],
  [72, "impulsive", "충동적인, 행동을 자극하는"],
  [73, "impulse", "충동, 자극, 충격"],
  [74, "dispel", "근심·의심 등을 떨쳐 버리다, 없애다"],
  [75, "impel", "몰아대다, 재촉하다, 앞으로 나아가게 하다"]
] as const;
