export const vocabDay21 = [
  [1, "local", "지방의, 지역의, 현지의"],
  [2, "locally", "지방적으로, 가까이에"],
  [3, "localize", "지방의 특색을 부여하다, 지역화하다"],
  [4, "localization", "지방화, 지방 분권"],
  [5, "locate", "~에 두다, 위치시키다, 위치를 알아내다"],
  [6, "location", "위치, 장소"],
  [7, "locational", "위치 선정의, 소재지의"],
  [8, "allocate", "할당하다, 배분하다, 배치하다"],
  [9, "allocation", "할당량, 할당액"],
  [10, "assign", "할당하다, 배정하다"],
  [11, "distribute", "나눠주다, 분배하다"],
  [12, "point", "손가락으로 가리키다, 지적하다; 점, 지점, 요점"],
  [13, "point out", "가리키다, 지적하다"],
  [14, "appoint", "시간·장소 등을 지정하다, 임명하다"],
  [15, "appointment", "약속, 예약"],
  [16, "designate", "지정하다, 임명하다"],
  [17, "nominate", "임명하다, 지명하다"],
  [18, "disappoint", "실망시키다"],
  [19, "disappointed", "실망한"],
  [20, "disappointing", "실망스러운"],
  [21, "disappointment", "실망"],
  [22, "punctuate", "구두점을 찍다, 일을 중단시키다"],
  [23, "punctuation", "구두점, 중단"],
  [24, "punctual", "시간을 잘 지키는, 규칙적인"],
  [25, "punctually", "시간대로, 엄수하여"],
  [26, "punctuality", "시간 엄수, 정확함"],
  [27, "confront", "직면하다, 맞서다, 닥치다"],
  [28, "confrontation", "직면, 대립"],
  [29, "frontier", "국경, 경계, 미개척 영역"],
  [30, "frontal", "정면의, 앞면의, 머리 앞부분의"],
  [31, "front", "앞면"],
  [32, "forefront", "선두, 맨 앞"],
  [33, "fund", "기금, 자금; 자금을 제공하다"],
  [34, "funding", "자금 제공, 재정 지원"],
  [35, "fundamental", "근본적인, 중요한; 기본 원리, 근본"],
  [36, "fundamentally", "근본적으로"],
  [37, "fundamentalism", "근본주의"],
  [38, "found", "설립하다, 세우다, 기반을 두다"],
  [39, "founder", "설립자"],
  [40, "foundation", "토대, 기반"],
  [41, "profound", "엄청난, 깊은, 심오한"],
  [42, "profoundly", "깊이, 극심하게"],
  [43, "profundity", "깊이, 심오함"],
  [44, "base", "맨 아랫부분, 기초, 본부; ~에 본부를 두다"],
  [45, "basement", "건물의 지하층, 지하실, 구조물의 최하부"],
  [46, "debase", "가치나 품위를 떨어뜨리다, 저하시키다"],
  [47, "medium", "매체, 수단, 중간; 중간의"],
  [48, "immediate", "즉각적인, 직접적인"],
  [49, "immediately", "즉시, 즉각"],
  [50, "mediation", "중재, 조정, 매개"],
  [51, "mediate", "중재하다, 조정하다"],
  [52, "mediator", "중재인, 조정관"],
  [53, "median", "중간의, 중간값의, 중앙의"],
  [54, "intermediate", "중간의, 중급의; 중간물, 중급자"],
  [55, "medieval(mediaeval)", "중세의, 중세풍의"],
  [56, "meditation", "명상, 심사숙고"],
  [57, "meditate", "명상하다"],
  [58, "midterm", "중간, 중간고사; 학기·임기 등의 중간의"],
  [59, "midst", "중앙, 한가운데"],
  [60, "in the midst of", "~의 한가운데에"],
  [61, "mean", "의미하다, 의도하다; 비열한; 수단"],
  [62, "meaning", "의미, 뜻"],
  [63, "meaningful", "의미 있는, 중요한"],
  [64, "meaningless", "의미 없는"],
  [65, "express", "표현하다, 나타내다"],
  [66, "indicate", "보여주다, 나타내다"],
  [67, "represent", "나타내다, 대표하다"],
  [68, "meanwhile", "그동안에, 한편"],
  [69, "central", "중앙의, 중심적인"],
  [70, "concentrate", "집중시키다, 집중하다"],
  [71, "egocentric", "자기중심적인, 이기적인"],
  [72, "ethnocentrism", "자기 민족 중심주의"],
  [73, "sum", "총합, 합계; 총합하다"],
  [74, "a large sum of money", "거액의 돈"],
  [75, "in sum", "요약하면, 결국"],
  [76, "summit", "산의 정상, 정점, 정상 회담"],
  [77, "summary", "요약, 개요; 간략한, 약식의"],
  [78, "summarize", "요약하다, 간추려 말하다"]
] as const;
