export const vocabDay25 = [
  [1, "metaphor", "은유, 비유, 상징"],
  [2, "metaphorical", "은유의, 비유의"],
  [3, "metabolism", "신진대사, 대사 작용"],
  [4, "metabolic", "신진대사의"],
  [5, "metamorphosis", "생물의 변태, 변형"],
  [6, "method", "방법, 방식, 체계"],
  [7, "advertise", "광고하다, 선전하다"],
  [8, "advertising", "광고, 광고업"],
  [9, "advertiser", "광고주"],
  [10, "advertisement", "광고"],
  [11, "convert", "바꾸다, 변환하다, 개조하다"],
  [12, "convertible", "바꿀 수 있는, 개조할 수 있는"],
  [13, "conversion", "전환, 개조"],
  [14, "convert A to/into B", "A를 B로 바꾸다"],
  [15, "alter", "바꾸다, 변경하다"],
  [16, "modify", "바꾸다, 수정하다"],
  [17, "transform", "변형하다, 변화시키다"],
  [18, "vertical", "수직의, 세로의; 수직선"],
  [19, "vertically", "수직으로"],
  [20, "version", "형태, 버전"],
  [21, "universe", "우주, 영역, 활동권"],
  [22, "universal", "일반적인, 전 세계적인, 보편적인"],
  [23, "universally", "일반적으로, 보편적으로"],
  [24, "university", "대학"],
  [25, "diverse", "다양한, 다른 종류의"],
  [26, "diversity", "다양성"],
  [27, "diversify", "다양화하다"],
  [28, "diversion", "전환, 방향 바꿈"],
  [29, "reverse", "뒤집다, 반전시키다; 반대, 반전"],
  [30, "reversible", "뒤집을 수 있는"],
  [31, "irreversible", "뒤집을 수 없는"],
  [32, "in reverse", "반대로, 거꾸로"],
  [33, "adverse", "부정적인, 불리한, 반대하는"],
  [34, "adversity", "역경, 고난"],
  [35, "contrary", "반대의, 반하는"],
  [36, "negative", "부정적인, 반대의"],
  [37, "converse", "대화하다; 정반대의, 거꾸로의; 반대"],
  [38, "conversely", "정반대로, 역으로"],
  [39, "conversation", "대화"],
  [40, "divorce", "이혼, 분리; 이혼하다, 분리하다"],
  [41, "extrovert", "외향적인, 외향적인 사람"],
  [42, "introvert", "내향적인; 내향적인 사람"],
  [43, "invert", "뒤집다, 거꾸로 하다, 뒤바꾸다"],
  [44, "distort", "비틀다, 왜곡하다, 일그러뜨리다"],
  [45, "distortion", "왜곡, 일그러짐"],
  [46, "torment", "고통, 고민거리; 고통을 주다, 괴롭히다"],
  [47, "retort", "대꾸하다, 쏘아붙이다; 말대꾸, 응수"],
  [48, "torture", "고문, 심한 고통; 고문하다, 괴롭히다"],
  [49, "simplicity", "단순함, 간단함"],
  [50, "simple", "단순한, 간단한"],
  [51, "simply", "단순하게, 간단히"],
  [52, "simplify", "간단하게 하다, 간소화하다"],
  [53, "complicate", "복잡하게 하다; 복잡한, 뒤얽힌"],
  [54, "complicated", "복잡한"],
  [55, "complication", "복잡함, 복잡한 문제"],
  [56, "uncomplicated", "복잡하지 않은, 단순한"],
  [57, "replicate", "복제하다, 반복되다"],
  [58, "replication", "복제한, 되풀이"],
  [59, "replicable", "복제 가능한, 반복 가능한"],
  [60, "replica", "복제품, 모형"],
  [61, "explicit", "분명한, 명백한, 솔직한"],
  [62, "explicitly", "명백하게"],
  [63, "explicate", "자세히 설명하다, 해명하다"],
  [64, "definite", "분명한, 확실한"],
  [65, "obvious", "분명한, 명백한"],
  [66, "specific", "구체적인, 분명한"],
  [67, "apply", "지원하다, 신청하다, 적용하다, 약 등을 바르다"],
  [68, "applicant", "지원자"],
  [69, "application", "지원, 적용"],
  [70, "appliance", "적용, 응용, 가정용 기기"],
  [71, "apply for", "~에 지원하다"],
  [72, "reply", "반응하다, 대답하다; 답장, 대답"],
  [73, "imply", "암시하다, 넌지시 내비치다"],
  [74, "implication", "암시, 함축"],
  [75, "implicit", "암시된, 내포된"],
  [76, "display", "드러내다, 전시하다; 전시"],
  [77, "employ", "고용하다, 이용하다"],
  [78, "employer", "고용주, 사용자"],
  [79, "employee", "고용인, 종업원"],
  [80, "employment", "고용, 직업"],
  [81, "unemployment", "실업"],
  [82, "exploit", "부당하게 이용하다, 개척하다; 위업, 공적"],
  [83, "complex", "복잡한, 복합의; 복잡하게 하다; 복합 건물, 합성물"],
  [84, "complexity", "복잡성"],
  [85, "perplex", "당황하게 하다, 혼란케 하다"],
  [86, "perplexity", "당황함"],
  [87, "duplicate", "복제하다; 중복의; 복제"],
  [88, "diploma", "졸업장, 학위, 수료 증서"],
  [89, "diplomat", "외교관, 외교/정치에 능한 사람"],
  [90, "multiple", "많은, 다수의, 다양한; 배수"]
] as const;
