export const vocabDay17 = [
  [1, "relate", "관련 짓다, 관련이 있다"],
  [2, "relation", "관련성, 관계"],
  [3, "relative", "관련 있는, 상대적인"],
  [4, "relatively", "비교적, 상대적으로"],
  [5, "be related to/with", "~과 관련 있다"],
  [6, "associate", "관련시키다, 연상하다"],
  [7, "connect", "연결하다, 이어지다"],
  [8, "correlation", "연관성, 상호 관련"],
  [9, "correlate", "연관성이 있다, 서로 관련시키다"],
  [10, "correlative", "상호 관계가 있는; 상관관계가 있는 것"],
  [11, "correlation between", "~ 사이의 상관관계"],
  [12, "translate", "번역하다, 해석하다"],
  [13, "translation", "번역, 통역"],
  [14, "translator", "번역가, 통역사"],
  [15, "translate into", "~로 번역하다"],
  [16, "congestion", "혼잡, 울혈, 인구 밀집"],
  [17, "congest", "혼잡하게 하다"],
  [18, "digest", "소화시키다; 요약문"],
  [19, "digestion", "소화"],
  [20, "digestive", "소화의, 소화를 돕는"],
  [21, "register", "등록하다, 신고하다; 등록부"],
  [22, "registration", "등록, 신고"],
  [23, "registry", "등록, 등기, 등기소"],
  [24, "register for", "~에 등록하다"],
  [25, "declare", "세관에 신고하다"],
  [26, "enroll", "등록하다, 입학시키다"],
  [27, "report", "보고하다, 신고하다"],
  [28, "exaggerate", "과장하다, 지나치게 강조하다"],
  [29, "exaggeration", "과장"],
  [30, "can hardly be exaggerated", "아무리 강조해도 지나치지 않다"],
  [31, "prefer", "더 좋아하다, 선호하다, 차라리 ~을 택하다"],
  [32, "preferred", "우선의"],
  [33, "preference", "선호"],
  [34, "preferential", "우선권을 주는"],
  [35, "prefer A to B", "B보다 A를 더 좋아하다"],
  [36, "refer", "참고하다, 언급하다, 인용하다"],
  [37, "reference", "참고, 언급"],
  [38, "referee", "심판, 보증인, 추천인"],
  [39, "refer to", "~을 참고하다"],
  [40, "conference", "회의, 회담, 학회"],
  [41, "confer", "상의하다"],
  [42, "differ", "다르다, 의견을 달리하다"],
  [43, "difference", "다름, 차이"],
  [44, "differentiate", "구별하다"],
  [45, "differ from", "~과 다르다"],
  [46, "disagree", "동의하지 않다, 의견이 다르다"],
  [47, "dissent", "반대하다, 의견을 달리하다"],
  [48, "indifferent", "무관심한, 무관한"],
  [49, "indifference", "무관심"],
  [50, "infer", "추론하다, 암시하다"],
  [51, "inference", "추론"],
  [52, "inferential", "추론의, 추정에 의한"],
  [53, "fertile", "비옥한, 다산의"],
  [54, "fertility", "비옥함"],
  [55, "fertilize", "비옥하게 하다"],
  [56, "fertilizer", "비료"],
  [57, "ferry", "사람·화물 운반용의 연락선; 나르다, 수송하다"],
  [58, "defer", "미루다, 연기하다, 경의를 표하다"],
  [59, "deferrable", "연기할 수 있는"],
  [60, "deference", "존경, 경의, 복종"],
  [61, "offer", "제공하다, 제안하다, 주다; 제공, 제안"],
  [62, "suffer", "고통받다, ~에 시달리다, 특성 등을 겪다"],
  [63, "transfer", "옮기다, 이동하다, 환승하다; 이동, 전학"],
  [64, "cast", "던지다, 그림자를 드리우다; 던지기"],
  [65, "cast doubt on", "~에 의문을 던지다, ~을 의심하다"],
  [66, "broadcast", "방송하다, 방영하다; 방송"],
  [67, "broadcasting", "방송업계"],
  [68, "broadcaster", "방송인, 방송사"],
  [69, "outcast", "버림받은, 쫓겨난; 버림받은 사람, 따돌려진 사람"],
  [70, "object", "물건, 대상, 목표; 반대하다"],
  [71, "objective", "객관적인"],
  [72, "objectively", "객관적으로"],
  [73, "objectivity", "객관성"],
  [74, "objection", "반대, 이의"],
  [75, "object to", "~에 반대하다"],
  [76, "subject", "지배하에 두다; ~의 지배하에 있는; 과목, 주제, 연구 대상, 백성/신하"],
  [77, "subjective", "주관의, 주관적인"],
  [78, "subjectivity", "주관성, 주관적인 일"],
  [79, "be subject to", "~의 지배하에 있다, ~을 조건으로 하다"],
  [80, "project", "연구 과제, 사업; 계획하다, 투사하다"],
  [81, "projection", "투사된 영상, 예상"],
  [82, "projector", "영사기"],
  [83, "reject", "거절하다, 거부하다, 부인하다"],
  [84, "rejection", "거부, 거절"],
  [85, "decline", "거절하다, 사양하다"],
  [86, "deny", "거부하다, 부인하다"],
  [87, "refuse", "거부하다, 거절하다"],
  [88, "inject", "주사하다, 주입하다"],
  [89, "injection", "주사"],
  [90, "eject", "튀어나오게 하다, 쫓아내다"],
  [91, "ejection", "방출, 분출"]
] as const;
