export const englishMeaningMap: Record<string, string[]> = {
  protect: ["보호하다", "지키다", "막다"],
  protection: ["보호", "보호물", "방어"],
  protective: ["보호하는", "보호용의"],
  defend: ["방어하다", "지키다"],
  guard: ["지키다", "보호하다", "경계하다"],
  preserve: ["보존하다", "지키다"],
  secure: ["확보하다", "안전하게 하다"],
  propose: ["제안하다", "청혼하다", "제시하다"],
  proposal: ["제안", "청혼", "계획안"],
  prospect: ["전망", "가능성", "예상"],
  proactive: ["사전 대처하는", "적극적인"],
  progress: ["진전", "발전하다", "진행"],
  make_progress: ["진전을 이루다", "발전하다"],
  profile: ["윤곽", "인물 소개", "프로필"],
  predict: ["예측하다", "예견하다"],
  prediction: ["예측", "예언"],
  predictable: ["예측 가능한"],
  preview: ["미리 보기", "예고편"],
  preoccupy: ["사로잡다", "몰두하게 하다"],
  precaution: ["예방책", "조심", "경계"],
  premature: ["너무 이른", "시기상조의"],
  previous: ["이전의", "앞선"],
  foresee: ["예견하다", "내다보다"],
  forecast: ["예보", "예측하다"],
  anticipate: ["예상하다", "기대하다"],
  expect: ["기대하다", "예상하다"],
  ancient: ["고대의", "오랜"],
  ancestor: ["조상", "선조"],
  anchor: ["닻", "고정시키다"],
  replace: ["대체하다", "바꾸다"],
  replacement: ["대체물", "교체"],
  respect: ["존중하다", "존경", "측면"],
  retire: ["은퇴하다", "물러나다"],
  refuge: ["피난처", "보호처"],
  refugee: ["난민"],
  remain: ["남다", "여전히 ~이다"],
  research: ["연구", "연구하다"],
  recycle: ["재활용하다"],
  remarkable: ["주목할 만한", "놀라운"],
  restore: ["회복하다", "복구하다"],
  reconcile: ["화해시키다", "조화시키다"],
  withdraw: ["철수하다", "인출하다"],
  withhold: ["보류하다", "주지 않다"],
  withstand: ["견디다", "버티다"],
  postpone: ["연기하다", "미루다"],
  byproduct: ["부산물"],
  parallel: ["평행한", "유사한"],
  parasite: ["기생충", "기생하는 사람"],
  paradox: ["역설"],
  upcoming: ["다가오는", "곧 있을"],
  update: ["업데이트하다", "최신 정보"],
  uphold: ["지지하다", "유지하다"],
  superior: ["우수한", "상급의"],
  surroundings: ["주변 환경"],
  surround: ["둘러싸다"],
  surrender: ["항복하다", "포기하다"],
  overall: ["전반적인", "전체적으로"],
  overwhelm: ["압도하다", "당황하게 하다"],
  overlook: ["간과하다", "내려다보다"],
  overcome: ["극복하다"],
  overtake: ["추월하다", "앞지르다"],
  overseas: ["해외로", "해외의"],
  depict: ["묘사하다", "그리다"],
  delicate: ["섬세한", "연약한"],
  desire: ["원하다", "욕구"],
  derive: ["끌어내다", "유래하다"],
  detect: ["감지하다", "발견하다"],
  depart: ["출발하다", "떠나다"],
  admire: ["존경하다", "감탄하다"],
  admiration: ["감탄", "존경"],
  appreciate: ["감사하다", "가치를 알아보다"],
  approach: ["접근하다", "방식", "다가가다"],
  assure: ["확신시키다", "보장하다"],
  confirm: ["확인하다", "확정하다"],
  convince: ["납득시키다", "설득하다"],
  persuade: ["설득하다"],
  asset: ["자산", "강점"],
  accumulate: ["축적하다", "모으다"],
  accelerate: ["가속화하다", "촉진하다"],
  alarm: ["불안하게 하다", "경보"],
  aspect: ["측면", "양상"],
};

export function normalizeTerm(term: string) {
  return term
    .toLowerCase()
    .replace(/\s+/g, "_")
    .replace(/[^a-z_]/g, "");
}

export function getMeanings(term: string) {
  const normalized = normalizeTerm(term);
  return englishMeaningMap[normalized] ?? ["의미 정리 중", "기본 뜻 확인 필요"];
}
